export const navData = {
	store: {
		title: "shop",
		data: [
			"Shop the latest",
			"Mac",
			"Ipad",
			"Iphone",
			"Apple Watch",
			"Accessories",
		],
		quickLinks_title: "Quick Links",
		linksData: ["Find a Store", "Order Status", "Financing", "Apple Trade In"],
		specials_title: "Shop Special Stores",
		specials_links: [
			"Certified Refurbished",
			"Education",
			"Business",
			"Veterans & Military",
			"Government",
		],
	},
	mac: {
		title: "Explore mac",
		data: [
			"Macbook Air",
			"Macbook Pro",
			"iMac",
			"Mac mini",
			"Mac studio",
			"Mac Pro",
			"Displays",
		],
		shopMac_title: "Shop Mac",
		shopMac_links: [
			"Shop Mac",
			"Mac Accessories",
			"Financing",
			"Apple Trade in",
		],
		moreMac_title: "More from Mac",
		moreMac_links: [
			"Mac Support",
			"macOS Ventura",
			"Continuity",
			"iCloud",
			"Mac for Business",
			"Education",
		],
	},
	ipad: {
		title: "Explore iPad",
		data: ["iPad Pro", "iPad Air", "iPad Mini", "Apple Pencil", "Keyboards"],
		shopIpad_title: "Shop iPad",
		shopIpad_links: [
			"Shop iPad",
			"iPad Accessories",
			"Financing",
			"Apple Trade in",
		],
		moreIpad_title: "More from iPad",
		moreIpad_links: ["iPad Support", "iPadOS Ventura", "iCloud", "Education"],
	},
	iphone: {
		title: "Explore iPhone",
		data: ["iPhone 14 Pro", "iPhone 14", "iPhone 13", "iPhone 12", "iPhone SE"],
		shopIphone_title: "Shop iPhone",
		shopIphone_links: [
			"Shop iPhone",
			"iPhone Accessories",
			"Apple Trade in",
			"Carrier Deals",
			"Financing",
		],
		moreIphone_title: "More from iPhone",
		moreIphone_links: [
			"iPhone Support",
			"iOS 16",
			"iPhone Privacy",
			"iCloud",
			"Wallet,Pay,Card",
			"Siri",
		],
	},
	appleWatch: {
		title: "Explore Watch",
		data: [
			"Apple Watch Ultra",
			"Apple Watch Series 8",
			"Apple Watch Series SE",
			"Apple Watch Nike",
			"Apple Watch Hermes",
		],
		shopWatch_title: "Shop Watch",
		shopWatch_links: [
			"Shop Apple Watch",
			"Apple Watch Studio",
			"Apple Watch Bands",
			"Apple Watch Accessories",
			"Financing",
			"Apple Trade In",
		],
		moreWatch_title: "More from Watch",
		moreWatch_links: ["Apple Watch Support", "watchOS 9", "Apple FItness+"],
	},
	airpods: {
		title: "Explore Airpods",
		data: [
			"AirPods 2nd generation",
			"AirPods 3nd generation",
			"AirPods Pro 2nd generation",
			"AirPods Max",
		],
		shopPods_title: "Shop Airpods",
		shopPods_links: ["Shop AirPods", "AirPods Accessories"],
		morePods_title: "More from AirPods",
		morePods_links: ["AirPods Support", "Apple Music"],
	},
	tv: {
		title: "Explore TV & Home",
		data: ["Apple TV 4K", "HomePod", "HomePod mini"],
		shopTV_title: "Shop Tv & Home",
		shopTV_links: [
			"Shop Apple TV",
			"Shop HomePod",
			"Shop HomePod mini",
			"Shop Siri Remote",
			"TV & Home Accessories",
		],
		moreTV_title: "More from TV & Home",
		moreTV_links: [
			"Apple TV Support",
			"HomePod Support",
			"Apple TV App",
			"Apple TV+",
			"Home App",
			"Apple Music",
			"Siri",
			"Aiplay",
		],
	},
	entertainment: {
		title: "Explore Entertainment",
		data: [
			"Apple One",
			"Apple TV+",
			"Apple Music",
			"Apple Arcade",
			"Apple Fitness+",
			"Apple News+",
			"Apple Podcasts",
			"Apple Books",
			"App Store",
		],
		entertainment_title: "Support",
		entertainment_links: ["Apple TV+ Support", "Apple Music Support"],
	},
	accessories: {
		title: "Shop Accessories",
		data: ["Mac", "iPad", "iPhone", "Apple Watch", "AirPods", "TV & Home"],
		explore_accessories_title: "Explore Accessories",
		explore_accessories_links: ["Made by Apple", "Beats by Dr.Dre", "AirTag"],
	},
	support: {
		title: "Explore Support",
		data: ["iPhone", "Mac", "iPad", "Watch", "AirPods", "Music", "TV"],
		getHelp_title: "Get Help",
		getHelp_links: ["Communities", "Check Coverage", "Repair", "Contact Us"],
		helpful_topics_title: "Helpful Topics",
		helpful_topics_links: [
			"Get AppleCare+",
			"Apple ID & Password",
			"Billing & Subscriptions",
			"Find My",
			"Accessibility",
		],
	},
};
